#!/usr/bin/env python3

"""Convert asciidoc to HTML via XSL templates

Usage: ./asciipress ASCIIDOC-DIR OUTPUT-DIR [-q | --quiet]

Options:
  -h --help   Show these instructions and exit
  -q --quiet  Suppress console output
  --version   Show version and exit

"""

def main(args):
    csol = console.Silent() if args['--quiet'] else console.Print()
    cfg  = config.create(args)
    exitcode = process(csol, cfg)
    return exitcode

def process(console, config):
    files = articles.scan(config['ASCIIDOC-DIR'], config['OUTPUT-DIR'])
    pub = publisher.Publisher(console)
    summary = pub.to_html(files, config['templates']['article'])

    console.echo("Generated %s HTML files" % len(files))

    # if len(files):
        # new index and rss file

if __name__ == '__main__':
    import shutil, sys
    
    for pkg in ['asciidoc', 'xsltproc']:
        if shutil.which(pkg) is None:
            print("Dependency not found. Please install " + pkg)
            sys.exit(1)

    sys.path.insert(1, sys.path[0] + '/lib')

    import console, config, articles, publisher
    from docopt import docopt
    args = docopt(__doc__, version='1.0.0')
    retval = main(args)

    if isinstance(retval, int):
        sys.exit(retval)